//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class empDetail
    {
        public int id { get; set; }
        public string name { get; set; }
        public string department { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
